#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : at
Version  : 3.1.20
Release  : 13
URL      : http://localhost/cgit/projects/at/snapshot/at-3.1.20.tar.bz2
Source0  : http://localhost/cgit/projects/at/snapshot/at-3.1.20.tar.bz2
Source1  : atd.service
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: at-bin = %{version}-%{release}
Requires: at-license = %{version}-%{release}
Requires: at-man = %{version}-%{release}
Requires: at-services = %{version}-%{release}
Requires: at-setuid = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : bison
BuildRequires : flex
BuildRequires : flex-dev
BuildRequires : msmtp
BuildRequires : perl(Test::More)
Patch1: 0001-Remove-owner-group-setting-on-install.patch

%description
This is version of 3.1.x of at, for running commands at a
specified time.  To install, do a

%package bin
Summary: bin components for the at package.
Group: Binaries
Requires: at-setuid = %{version}-%{release}
Requires: at-license = %{version}-%{release}
Requires: at-services = %{version}-%{release}

%description bin
bin components for the at package.


%package doc
Summary: doc components for the at package.
Group: Documentation
Requires: at-man = %{version}-%{release}

%description doc
doc components for the at package.


%package license
Summary: license components for the at package.
Group: Default

%description license
license components for the at package.


%package man
Summary: man components for the at package.
Group: Default

%description man
man components for the at package.


%package services
Summary: services components for the at package.
Group: Systemd services

%description services
services components for the at package.


%package setuid
Summary: setuid components for the at package.
Group: Default

%description setuid
setuid components for the at package.


%prep
%setup -q -n at-3.1.20
cd %{_builddir}/at-3.1.20
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604881448
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static --with-jobdir=/var/spool --with-atspool=/var/spool/atspool
make

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
export SOURCE_DATE_EPOCH=1604881448
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/at
cp %{_builddir}/at-3.1.20/COPYING %{buildroot}/usr/share/package-licenses/at/4d1d37f306ed270cda5b2741fac3abf0a7b012e5
cp %{_builddir}/at-3.1.20/Copyright %{buildroot}/usr/share/package-licenses/at/fac3ce06c12ddc1a827b51cf0385cc5ef2046637
make install IROOT="%{buildroot}" docdir=/usr/share/doc
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/atd.service
## install_append content
rm "%{buildroot}/var/spool/.SEQ"
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/atd
/usr/bin/atq
/usr/bin/atrm
/usr/bin/atrun
/usr/bin/batch

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/at/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/at/4d1d37f306ed270cda5b2741fac3abf0a7b012e5
/usr/share/package-licenses/at/fac3ce06c12ddc1a827b51cf0385cc5ef2046637

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/at.1
/usr/share/man/man1/atq.1
/usr/share/man/man1/atrm.1
/usr/share/man/man1/batch.1
/usr/share/man/man5/at.allow.5
/usr/share/man/man5/at.deny.5
/usr/share/man/man8/atd.8
/usr/share/man/man8/atrun.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/atd.service

%files setuid
%defattr(-,root,root,-)
%attr(4755, root, root) /usr/bin/at
