#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : at
Version  : 3.1.20
Release  : 8
URL      : http://localhost/cgit/projects/at/snapshot/at-3.1.20.tar.bz2
Source0  : http://localhost/cgit/projects/at/snapshot/at-3.1.20.tar.bz2
Source1  : atd.service
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: at-bin
Requires: at-config
Requires: at-doc
BuildRequires : Linux-PAM-dev
BuildRequires : bison
BuildRequires : flex
BuildRequires : flex-dev
BuildRequires : msmtp
Patch1: 0001-Remove-owner-group-setting-on-install.patch

%description
This is version of 3.1.x of at, for running commands at a
specified time.  To install, do a

%package bin
Summary: bin components for the at package.
Group: Binaries
Requires: at-config

%description bin
bin components for the at package.


%package config
Summary: config components for the at package.
Group: Default

%description config
config components for the at package.


%package doc
Summary: doc components for the at package.
Group: Documentation

%description doc
doc components for the at package.


%prep
%setup -q -n at-3.1.20
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1510691482
%configure --disable-static --with-jobdir=/var/spool --with-atspool=/var/spool/atspool
make V=1

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
export SOURCE_DATE_EPOCH=1510691482
rm -rf %{buildroot}
make install IROOT="%{buildroot}" docdir=/usr/share/doc
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/atd.service
## make_install_append content
rm "%{buildroot}/var/spool/.SEQ"
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/at
/usr/bin/atd
/usr/bin/atq
/usr/bin/atrm
/usr/bin/atrun
/usr/bin/batch

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/atd.service

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/at/*
%doc /usr/share/man/man1/*
%doc /usr/share/man/man5/*
%doc /usr/share/man/man8/*
